<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <UseWPF>true</UseWPF>
    <AssemblyName>BikeRentalOpdracht</AssemblyName>
    <RootNamespace>BikeRentalOpdracht</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="view\StoresEdit - Copy.xaml.cs" />
  </ItemGroup>

  <ItemGroup>
    <Page Remove="view\StoresEdit - Copy.xaml" />
  </ItemGroup>

</Project>